modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"

[[mods]]
modId="valcon"
version="0.5"
displayName="Valcon"
description='''
An addon and core mod for the Starfell modpacks. Let the stars guide you!
'''

[[dependencies.valcon]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.valcon]]
modId="farmersdelight"
type="required"
versionRange="[1.2.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.valcon]]
modId="nomansland"
type="required"
versionRange="[1.4.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.valcon]]
modId="block_factorys_bosses"
type="required"
versionRange="[1.0.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.valcon]]
modId="biolith"
type="required"
versionRange="[3.0.10,)"
ordering="AFTER"
side="BOTH"